spring:
  profiles:
    active: dev
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 13001
spring:
  profiles: dev
  application:
    name: springcloud-config-server-dev
---
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
server:
  port: 13002
spring:
  profiles: test
  application:
    name: springcloud-config-server-test
